# Generated by Django 5.0.4 on 2024-05-26 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        ('subjects', '0005_subject_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionMCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.TextField(max_length=700)),
                ('answer1', models.TextField(max_length=200)),
                ('answer2', models.TextField(max_length=200)),
                ('answer3', models.TextField(max_length=200)),
                ('answer4', models.TextField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
            ],
            options={
                'verbose_name': 'QuestionMCQ',
                'verbose_name_plural': "QuestionMCQ's",
            },
        ),
    ]
