# Generated by Django 5.0.4 on 2024-05-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_questionmcq'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_id',
            field=models.IntegerField(default=0),
        ),
    ]
