# Generated by Django 5.0.4 on 2024-05-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_alter_subject_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
