# Generated by Django 5.0.4 on 2024-05-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_rename_slug_subject_slugy'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='hours',
            field=models.IntegerField(default=0),
        ),
    ]
